### ISSUE TITLE
How to split the dataset?

### ISSUE THREAD

**Issue by wanyao1992** [khanhptnk/bandit-nmt#1]
Dear author,

Thank you for sharing the code with high quality. In your code you split the training dataset as train_src for init vocabulary, train_xe_src for supervised learning and train_pg_src for policy gradient. Can I consider the three datasets as the same? If not, how should I split my dataset?

Any help from you is highly appreciated.

**Comment by khanhptnk** [comment]
Thanks, train_src is the concatenation of train_xe_src and train_pg_src. But, in fact, train_xe_src and train_pg_src highly overlap each other. I think if you follow my instruction in README.md, the data is automatically split.
