### ISSUE TITLE
How to estimate the V value?

### ISSUE THREAD

**Issue by ganji15** [khanhptnk/bandit-nmt#2]
@khanhptnk 
Dear author, I am new to reinforcement learning and I am confused about the estimation of V value in your implementation.  As you known, let  **V (y^\hat _{<t} , x)**  denote the current V value estimation, then **V (y^\hat _{<t} , x)** should approximate the excepted future reward ,i.e., **r_{t+1} +r_{t+2} + ... + r_{T}** ;  in your implementation,  **V (y^\hat _{<t} , x)** is estimated by minimizing the MSE between itself and the ture value **R(y^\hat, x)**, i.e.,  **\min [V (y^\hat _{<t} , x) - R(y^\hat, x)]^2**, where I guess that **R(y^\hat, x)** is the final reward rather than the excepted future reward **r_{t+1} +r_{t+2} + ... + r_{T}** . So, my question is why the  V value can be estimated in that way ( and it seems that MIXER also estimates the V value in such a way)? Appearently,   **V (y^\hat _{<t} , x)** should approximate the excepted future reward instead of final reward **R(y^\hat, x)**, is that right? I will be grateful if you could provide me some explainations/suggestions.

**Comment by khanhptnk** [comment]
Thanks for your question. In our setup, the rewards are only non-zero at the final step so r_{t+1} +r_{t+2} + ... + r_{T} = r_{T} = R(y^\hat, x).

**Comment by ganji15** [comment]
@khanhptnk 
Thanks a lot.  You are right and I didn't figure out this trick before.
Still, I have another question. As you said, **r_{t+1} +r_{t+2} + ... + r_{T} = r_{T} = R(y^\hat, x)**, and my question is whether **R(y^\hat, x)** (used for V value estimation) is  estimated with another MC sampling trajectory instead of the current sampling one? Because if **R(y^\hat, x)** is estimated with the same MC sampling trajectory, the centered reward **\overline{R}(y^\hat, x)**  will be zero. Therefore, **R(y^\hat, x)**  (used for V value estimation) is actually estimated with 1-time (or k-times) ROLLOUT, is that right? Could you help me out with this question?

**Comment by khanhptnk** [comment]
We draw a single sample to estimate both the actor loss and the critic loss. I don't really see why using the same sample would make R_bar being zero. R_bar is the difference between an estimated mean reward and a sampled reward. In expectation, these two match but empirically they hardly coincide unless the model has stopped improving.

**Comment by ganji15** [comment]
@khanhptnk 
Thanks very much for your kind help! Moreover, your research paper is excellent and very inspiring.

**Comment by khanhptnk** [comment]
You are welcome. It's my pleasure to help :)
