### ISSUE TITLE
error while run  extract_data_de_en.sh

### ISSUE THREAD

**Issue by SeekPoint** [khanhptnk/bandit-nmt#3]
x en-de/train.tags.en-de.de
x en-de/train.tags.en-de.en
Preprocessing...

pre-processing train data...
Tokenizer Version 1.1
Language: de
Number of threads: 8
WARNING: No known abbreviations for language 'de', attempting fall-back to English version...
ERROR: No abbreviations files found in /Users//bandit-nmt/data/scripts/../share/nonbreaking_prefixes

Tokenizer Version 1.1
Language: en
Number of threads: 8
WARNING: No known abbreviations for language 'en', attempting fall-back to English version...
ERROR: No abbreviations files found in /Users//bandit-nmt/data/scripts/../share/nonbreaking_prefixes

clean-corpus.perl: processing prep/tmp/train_2014.en-de.tok.de & .en to prep/tmp/train_2014.en-de.clean, cutoff 1-50, ratio 9

Input sentences: 0  Output sentences:  0
Tokenizer Version 1.1
Language: de
Number of threads: 8
WARNING: No known abbreviations for language 'de', attempting fall-back to English version...
ERROR: No abbreviations files found in /Users//bandit-nmt/data/scripts/../share/nonbreaking_prefixes

**Comment by Isminoula** [comment]
Hello @loveJasmine,

I was able to solve this by changing line 32 in tokenizer.perl
from my $mydir = "$RealBin/../share/nonbreaking_prefixes";
to my $mydir = "$RealBin/";

Hope this helps!

**Comment by SeekPoint** [comment]
it works.  thanks!
