### ISSUE TITLE
What are the env variables

### ISSUE THREAD

**Issue by zjjj** [khanhptnk/bandit-nmt#5]
Thanks for sharing this project, but what should I use for the environment variable $YOUR_DATA and $YOUR_MODEL as instructed in README?

**Comment by khanhptnk** [comment]
Thanks. 
$YOUR_DATA is folder where the .pt data file is saved. It will be printed when you run preprocess.py. 
$YOUR_MODEL is a path to a checkpoint in -save_dir, where the model checkpoints are saved.

**Comment by zjjj** [comment]
Thanks. That works for me.
